### ISSUE TITLE
Path-to-regexp buggs methods / routes?

### ISSUE THREAD

**Issue by xarielah** [instantcommerce/next-api-decorators#530]
Hey since yesterday I'm experiencing in my newly created project a bug where I set the handler, and methods (ex. /api/auth/register) and it works fine, but as soon as I installed path-to-regexp all my default (non-regexp paths) paths have broken.

For example:
![image](https://user-images.githubusercontent.com/84734223/211484117-51d8b18b-2b01-4906-b606-20d0e077a915.png)
![image](https://user-images.githubusercontent.com/84734223/211484141-996fcdee-dcb8-4241-8f15-fe385f401705.png)

but the regexp paths do work just fine.

My files were set to be:
- /api/
- - /auth/
- - - register.ts
- - - login.ts

I also tried:
- /api/
- - /auth/
- - - /register/
- - - - index.ts // [[...params]].ts
- - - /login/
- - - - index.ts // [[...params]].ts

and still it does not work (sometimes it does, but in a weird way - to doesn't then it does, and then it doesn't).

**Comment by xarielah** [comment]
@ggurkal

**Comment by ggurkal** [comment]
Hi @xarielah 

Thanks for the report!

There was a fix that was only released in the beta channel, but now it's released under `v2.0.1` which should fix what you are experiencing.

Feel free to re-open if your problem persists.

**Comment by JamesIde** [comment]
I don't have anything to say but this product excites me in ways I didn't know possible. Next API routes with NestJS decorators is awesome...
