### ISSUE TITLE
@Catch all decorator does not pass through the error thrown, but always is of type `InternalServerErrorException`

### ISSUE THREAD

**Issue by icazemier** [instantcommerce/next-api-decorators#551]
Hi,

I'm using : 

```

    "next": "^13.1.6",
    "next-api-decorators": "^2.0.1",

```

With a Catch all handler:

```typescript
const exceptionHandler = (error: unknown, req: NextApiRequest, res: NextApiResponse) => {
  if (!(error instanceof HttpException)) {
    console.warn('Unhandled error for url', error, req?.url);
    res.status(500).send('Unhandled error');
    return;
  }
  res.status(error?.statusCode ?? 500).send(error?.message ?? 'Unhandled');
};

@Catch(exceptionHandler)
class SomeHandler {
   ...
}
```

But it always passes a `InternalServerErrorException`:
![image](https://user-images.githubusercontent.com/64091093/219352539-7989c783-7f41-42ed-893d-042b4c9d778d.png)

While I throw:
```typescript
        const exception = new HttpException(401, data?.message ?? 'Unknown');
        throw exception;
```

or for that matter:

```typescript
        const exception = new UnauthorizedException( data?.message ?? 'Unknown');
        throw exception;
```

# Expected:
The message is passed through, but the status code is not!
Sometimes I just want to pass through the http status code together with the message 🙏🏻

**Comment by ggurkal** [comment]
Hi @icazemier 

Can't replicate the issue you're having. Please provide a minimum reproducible repo.

**Comment by icazemier** [comment]
Oh no! I can't reproduce it either on a dedicated project: https://github.com/icazemier/nextjs-api-decorator-catch-all

Let's close this ticket, excuse me for the fuss.
