### ISSUE TITLE
Not understanding how to structure API files using this library

### ISSUE THREAD

**Issue by alaughlin** [instantcommerce/next-api-decorators#559]
Apologies if this maybe more related to NextJS itself, but I am struggling understanding how to get routing properly working using this library.

Here's what `src/pages/api/address/[[...params]].ts` looks like:
```
class AddressHandler {
    @Post('/:userId')
    create(
        @Param('userId') userId: string,
        @Body() address: Address
    ): Promise<Address> {
        return this.addressService.createAddress(address, userId);
    }

    @Patch('/:userId')
    updateAddress(
        @Param('userId') userId: string,
        @Body() address: Partial<Address>,
    ): Promise<Address> {
        return this.addressService.updateAddress(address, userId);
    }
}

export default createHandler(AddressHandler);
```

And when I try to POST some data to `/api/address/randomUserId`, it gives back a 404. I suspect I might have not structured my files correctly, is there something I am missing here?

**Comment by jacekjagiello** [comment]
The route matching depends on [path-to-regexp](https://www.npmjs.com/package/path-to-regex) package, make sure you have it installed.

**Comment by alaughlin** [comment]
@jacekjagiello I have the [path-to-regexp](https://www.npmjs.com/package/path-to-regex) package installed. Does it need to be imported anywhere first?

**Comment by alaughlin** [comment]
ok, things seem to be really confusing and not working as intended. I attempted to take the example from here: https://next-api-decorators.vercel.app/docs/routing/route-matching and use it in my own project as a sanity check, and it's not working.

`src/pages/api/user/[[...params]].ts`

```
import { createHandler, Get, Param } from 'next-api-decorators';

class UserHandler {
    @Get()
    public list() {
        return 'GET /';
    }

    @Get('/:id')
    public details(@Param('id') id: string) {
        return `GET /${id}`;
    }

    @Get('/:userId/comments')
    public comments(@Param('userId') userId: string) {
        return `GET /${userId}/comments`;
    }

    @Get('/:userId/comments/:commentId')
    public commentDetails(@Param('userId') userId: string, @Param('commentId') commentId: string) {
        return `GET /${userId}/comments/${commentId}`;
    }
}

export default createHandler(UserHandler);
```

If I `GET` any route under `/api/user` it seems to always match the first `GET()` and invoke `list()`:
```
GET / -> returns 'GET /'
GET /1 -> returns 'GET /'
GET /1/comments -> returns 'GET /'
GET /1/comments/1 -> returns 'GET /'
```

If I disable the first route,  attempting to hit any of the nested routes results in a 404. Am I missing something here, or is something actually broken?

**Comment by ggurkal** [comment]
Hi @alaughlin 

Can't replicate the issue you're having. Please provide a minimum reproducible repo.

**Comment by alaughlin** [comment]
I figured out the issue. My project was part of a monorepo that also had a nestjs project, which included its own version of `path-to-regexp` and was somehow conflicting with the one required by `next-api-decorators`. I actually didn't need that project anymore so removing it solved the problem.
