### ISSUE TITLE
Any named export would fail from working in vercel 

### ISSUE THREAD

**Issue by yoty66** [instantcommerce/next-api-decorators#597]
Just spent a whole afternoon on that.

Reproduce: 

1. take any example. let's say the getting started example and add it a named export 

```
import { createHandler, Get } from 'next-api-decorators';


export const helloBug= ()=> {
return "hello bug" 
}

class UserHandler {
  @Get()
  public async users() {
    return await DB.findUsers();
  }
}

export default createHandler(UserHandler);
```

2. deploy it to staging 

3. call the EP and get a 404

**Comment by ggurkal** [comment]
Can't reproduce the error you're getting with the provided steps.

Please provide a minimum reproducible repository.
